---
services:
  - docker

language: python

python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7

install:
  - pip install --user -r requirements.txt

jobs:
  include:
    - stage: unit-tests
      name: "Unit Tests"
      script: python -m unittest discover