---
dist: xenial
services:
  - docker

language: python

python:
  - 3.7
  - 3.6
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - python -m unittest discover
  - >-
    dcb
    --snippetsdir .
    --snippet from.j2 ansible-playbook.j2
    --upstreamgroup andrewrothstein
    --upstreamapp docker-ansible
    --targetregistry foo-registry.bar.test
    --targetapp upgraded-docker-ansible
    --pullall
    --writeall
    --buildall
    --alltags alpine_latest archlinux_latest
