dist: xenial
services:
- docker
language: python
python:
- 3.7
- 3.6
- 3.5
install:
- pip install -r requirements.txt
- pip install .
script:
- python -m unittest discover
- >
  dcb
  --snippetsdir .
  --snippet from.j2 ansible-playbook.j2
  --upstreamgroup andrewrothstein
  --upstreamapp docker-ansible
  --targetregistry foo-registry.bar.test
  --targetapp upgraded-docker-ansible
  --pullall
  --writeall
  --buildall
  --alltags alpine_edge archlinux_latest
deploy:
  provider: pypi
  user: andrewrothstein
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: Fs5Sxe8mnHY8pxosHYOgfQ15yWkzpKCmDI+01ExchEJvNPNekZV9niZdNcsmejMxWNBzSBlJn89pNLnr4yQwIrtHrwgwb9Dn1UxhVpiZtD9pOCGrkcPb/AGrQGxVlaTTkKAiRhIAvNSBj6u2sU70g3391tNstsGNGHxbWAOkIIIU0hIy4z+OI+7lGWQ13j16cjDFHmCN1kTxBtcjAXLfQvLhXitfaT8PEkhQa4bHoLILpF+cnyKGfuXAQXHnMoPDVqR83sAl/baV1IT8cj94SVjvsldp7KHvCm944nXVaBWq94j3HV0k9vMEW+iq9oBuGCmAhq86kBA6VF0QMNNWcorxJPjz5Nax3BYk1q6CdOLTWyzc2m5fZEZrnr+vc/IKUWnt6N0O0CH56pMMMoM9YXj9Mt14Y5GCFJZmvI/2tgin9wXQIzc88EETI4i9VR6n6Azt9RB33BHLg5wPP17+MmcYuiB4qyZ36t3IAmEaSLsTXfXKVx4pEg+PEg637IxRS6L3anY7qQa3DYPxAwL17i1TXOC/V3/A6MWJ4wUmVZeI4J2OU0Ow48s8wEhOIIVV3Vqo4cHaS8/rJ4p8H/EZ6n4dGzyp+qnXzVw0RUCY32FbOsJEiDiXm8zKxChFkIqiwOG+WixQFwofWOeMhAm3kNHWzbj/4Jioqd24fYuWDcQ=
