---
- hosts: all
  roles:
    - andrewrothstein.pkg-upgrade
  tasks:
    - name: upgrade pip
      command: python -m pip install --upgrade pip
    - name: install dcb and test dependencies
      command: python -m pip install .[test]
    - name: dcb unit tests
      command: python -m unittest discover