---
- hosts: all
  roles:
    - andrewrothstein.pkg-upgrade
  tasks:
    - name: install dcb:latest
      pip:
        name: dcb
        state: latest
    - command: dcb --version
      register: dcb_test_output
    - name: dcb --version
      debug:
        msg: '{{ dcb_test_output.stdout }}'
