---
- hosts: all
  roles:
    - andrewrothstein.pkg-upgrade
    - andrewrothstein.docker-binaries
  tasks:
    - name: upgrade pip
      command: python3 -m pip install --upgrade pip
    - name: install dcb and test dependencies
      command: python3 -m pip install .[test]
    - name: dcb unit tests
      command: python3 -m unittest discover
    - command: dcb --help
      register: dcb_help
    - name: dcb --help
      debug:
        msg: '{{ dcb_help.stdout }}'