---
name: publish to (test.)pypi.org

on: push

jobs:
  build-n-publish:
    name: build and publish to (test.)pypi.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install task
        uses: arduino/setup-task@v1
      - name: task ver
        run: task --version
      - name: download task mono
        uses: actions/checkout@v2
        with:
          repository: andrewrothstein/tasks
          ref: develop
          path: taskmono
      - name: discovery python unit tests
        run: task -t taskmono/python-test.yml test
      - name: dcb integration test
        run: >-
          dcb
          --snippetsdir .
          --snippet from.j2 dcb-bootstrap.j2
          --upstreamregistry ghcr.io
          --upstreamgroup andrewrothstein
          --upstreamapp docker-ansible
          --targetregistry ghcr.io
          --targetuser ${{ github.actor }}
          --targetpwd ${{ github.token }}
          --pullall
          --writeall
          --buildall
          --pushall
          --alltags alpine_edge
      - name: build python package
        run: task -t taskmono/python-test.yml build
      - name: deploy to test.pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
      - name: deploy to pypi.org
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
